<?php
namespace App\Controller;
use Cake\Core\Configure;
use Cake\ORM\TableRegistry;
use Cake\I18n\Time;

/**
 * Created by 89ITWORLD.
 * User: Mahipal Singh
 * Date: 04-20-2016
 *
 */

class CouponsController extends AppController
{
 public function initialize()
 {
     parent::initialize(); // TODO: Change the autogenerated stub

     $this->Auth->allow(['index','details']);
 }

    public function index(){

    }
    public function details(){

    }

}