<?php
namespace App\Controller\Component;

use Cake\Controller\Component;

class ExpediaComponent extends Component{

    protected $url;
    protected $key;
    public function initialize(array $config)
    {
        parent::initialize($config); // TODO: Change the autogenerated stub
        $this->key='AbzP0JEDOkTmXeMYiMZkwq5PEsCJTigo';
        $this->url='http://terminal2.expedia.com/x/mflights/search?';
    }

    public function getFlights(array $options){
        $addUrl='';
        $url=$this->url.'apikey='.$this->key;
        foreach ($options as $option) {

        }
    }
}
?>